#ifndef HL2RP_SHAREDDEFS_H
#define HL2RP_SHAREDDEFS_H
#pragma once

#ifdef HL2RP_FULL
#define DECLARE_HL2RP_SERVERCLASS()         DECLARE_SERVERCLASS()
#define DECLARE_HL2RP_NETWORKCLASS()        DECLARE_NETWORKCLASS()
#define DECLARE_HL2RP_NETWORKCLASS_NOBASE() DECLARE_NETWORKCLASS_NOBASE()

#ifdef GAME_DLL
#define IMPLEMENT_HL2RP_NETWORKCLASS(classStem) IMPLEMENT_SERVERCLASS_ST(C##classStem, DT_##classStem)

#define HL2RP_FULL_FUNCTION
#define HL2RP_LEGACY_FUNCTION           {}
#define HL2RP_CLIENT_OR_LEGACY_FUNCTION {}
#else
#define IMPLEMENT_HL2RP_NETWORKCLASS(classStem) \
	IMPLEMENT_CLIENTCLASS(C_##classStem, DT_##classStem, C##classStem) \
	BEGIN_RECV_TABLE(C_##classStem, DT_##classStem)

#define HL2RP_CLIENT_OR_LEGACY_FUNCTION
#endif // GAME_DLL
#else
#define DECLARE_HL2RP_SERVERCLASS()
#define DECLARE_HL2RP_NETWORKCLASS()
#define DECLARE_HL2RP_NETWORKCLASS_NOBASE()
#define HL2RP_FULL_FUNCTION {}
#define HL2RP_LEGACY_FUNCTION
#define HL2RP_CLIENT_OR_LEGACY_FUNCTION
#endif // HL2RP_FULL

#define HALF_DAY_IN_MINUTES 720
#define ONE_DAY_IN_SECONDS  86400

// HUD positions, based off screen percentages
#define HL2RP_CENTER_HUD_SPECIAL_POS  -1.0f
#define HL2RP_MAIN_HUD_DEFAULT_X_POS   0.015f
#define HL2RP_MAIN_HUD_DEFAULT_Y_POS   0.03f
#define HL2RP_ZONE_HUD_DEFAULT_Y_POS   0.03f
#define HL2RP_ALERT_HUD_DEFAULT_Y_POS  0.2f
#define HL2RP_AIMING_HUD_DEFAULT_Y_POS 0.78f
#define HL2RP_COMM_HUD_DEFAULT_X_POS   0.82f
#define HL2RP_COMM_HUD_DEFAULT_Y_POS   0.62f

// HUD colors
#define HL2RP_HUD_COLOR_GREEN                      Color(0, 255, 0, 255)
#define HL2RP_MAIN_HUD_DEFAULT_NORMAL_TEXT_COLOR   Color(0, 0, 255, 255)
#define HL2RP_MAIN_HUD_DEFAULT_CRIMINAL_TEXT_COLOR Color(255, 0, 0, 255)
#define HL2RP_ALERT_HUD_DEFAULT_COLOR              COLOR_WHITE
#define HL2RP_ZONE_HUD_DEFAULT_COLOR               HL2RP_HUD_COLOR_GREEN
#define HL2RP_AIMING_HUD_DEFAULT_GENERAL_COLOR     HL2RP_HUD_COLOR_GREEN
#define HL2RP_AIMING_HUD_DEFAULT_PLAYER_COLOR      COLOR_WHITE
#define HL2RP_REGION_HUD_HEADER_DEFAULT_COLOR      Color(255, 150, 150, 255)
#define HL2RP_REGION_HUD_PLAYERS_DEFAULT_COLOR     Color(255, 100, 100, 255)

#define HL2RP_CONFIG_PATH "cfg/hl2rp/"

#define HL2RP_ENTITY_SEARCH_RADIUS_SQR (0.5f * 0.5f) // To be used during e.g. data loading

#define HL2RP_MAP_ALIAS_FIELD_NAME "mapAlias"

#define HL2RP_KEY_HINT_USER_MESSAGE "HL2RP_KeyHintText"

#define HL2RP_PLAYER_NAME_SAVE_MESSAGE           "HL2RP_SavePlayerName"
#define HL2RP_PROPERTY_UPDATE_USER_MESSAGE       "HL2RP_PropertyUpdated"
#define HL2RP_PROPERTY_GRANT_UPDATE_USER_MESSAGE "HL2RP_PropertyGrantUpdated"
#define HL2RP_CITY_ZONE_UPDATE_MESSAGE           "HL2RP_CityZoneUpdated"

#define HL2RP_LEARNED_HUD_HINTS_FIELD_NAME   "learnedHUDHints"
#define HL2RP_LEARNED_HUD_HINTS_UPDATE_EVENT "LearnedHUDHintsUpdated"

#define NETWORK_DIALOG_REWIND_SOUND "Buttons.snd9"
#define NETWORK_MENU_ITEM_SOUND     "Buttons.snd37"

#define HL2RP_PROPERTY_DOOR_LOCK_SOUND   "Buttons.snd28"
#define HL2RP_PROPERTY_DOOR_UNLOCK_SOUND "Buttons.snd21"

SCOPED_ENUM(EFaction, // NOTE: Don't change order
	Citizen,
	Combine
)

SCOPED_ENUM(EPlayerModelType, // NOTE: Don't change order
	Job,
	Citizen,
	VIPCitizen,
	Admin, // Generic admin
	Root
)

#endif // !HL2RP_SHAREDDEFS_H
