#ifndef HL2RP_SHAREDDEFS_H
#define HL2RP_SHAREDDEFS_H
#pragma once

#ifdef HL2RP_FULL
#define DECLARE_HL2RP_SERVERCLASS()  DECLARE_SERVERCLASS()
#define DECLARE_HL2RP_NETWORKCLASS() DECLARE_NETWORKCLASS()
#define HL2RP_LEGACY_FUNCTION {}

#define IMPLEMENT_HL2RP_NETWORKCLASS(classStem) \
	IMPLEMENT_NETWORKCLASS_ALIASED(classStem, DT_##classStem) \
	BEGIN_NETWORK_TABLE(C##classStem, DT_##classStem)
#else
#define DECLARE_HL2RP_SERVERCLASS()
#define DECLARE_HL2RP_NETWORKCLASS()
#define HL2RP_LEGACY_FUNCTION
#endif // HL2RP_FULL

// HUD positions, based off 640x480 resolution per client API
#define HL2RP_CENTER_HUD_SPECIAL_POS   -1
#define HL2RP_MAIN_HUD_DEFAULT_X_POS   10
#define HL2RP_MAIN_HUD_DEFAULT_Y_POS   15
#define HL2RP_ALERT_HUD_DEFAULT_Y_POS  30
#define HL2RP_AIMING_HUD_DEFAULT_Y_POS 375

// HUD colors
#define HL2RP_HUD_COLOR_GREEN                      Color(0, 255, 0, 255)
#define HL2RP_MAIN_HUD_DEFAULT_NORMAL_TEXT_COLOR   Color(0, 0, 255, 255)
#define HL2RP_MAIN_HUD_DEFAULT_CRIMINAL_TEXT_COLOR Color(255, 0, 0, 255)
#define HL2RP_ALERT_HUD_DEFAULT_COLOR              HL2RP_HUD_COLOR_GREEN
#define HL2RP_AIMING_HUD_DEFAULT_GENERAL_COLOR     HL2RP_HUD_COLOR_GREEN
#define HL2RP_AIMING_HUD_DEFAULT_PLAYER_COLOR      Color(255, 255, 255, 255)

#define HL2RP_KEY_HINT_USER_MESSAGE "HL2RPKeyHintText"

#define HL2RP_LEARNED_HUD_HINTS_FIELD_NAME        "learnedHUDHints"
#define HL2RP_LEARNED_HUD_HINTS_UPDATE_EVENT_NAME "LearnedHUDHintsUpdated"

#endif // !HL2RP_SHAREDDEFS_H
